testing

diff --git a/.github/workflows/find_branch.yml b/.github/workflows/find_branch.yml
--- a/.github/workflows/find_branch.yml
+++ b/.github/workflows/find_branch.yml
@@ -4,6 +4,7 @@ on:
     tags:
       - v*
 jobs:
+
   refParse:
     runs-on: ubuntu-latest
     steps:
@@ -51,3 +52,34 @@ jobs:
           branch=${raw/origin\/}
           echo BRANCH=$branch >> $GITHUB_ENV
       - run: echo ${{ env.BRANCH }}
+  checkBranches:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout source code
+        uses: actions/checkout@v2
+      - run: git fetch --prune --unshallow
+      - name: Get Branch
+        run: |
+          raw=$(git branch -r --contains ${{ github.ref }})
+          branch=${raw/origin\/}
+          echo BRANCH=$branch >> $GITHUB_ENV
+      - run: echo ${{ env.BRANCH }}
+      - run: |
+          BRANCHES=$(git branch -r --contains v5)
+          echo "BRANCHES is '${BRANCHES}'"
+          # Check for no branches explicitly...Otherwise echo adds a newline so wc thinks there's
+          # one branch.  And echo -n makes it appears that there's one less branch than there
+          # actually is.
+          if [ -z "$BRANCHES" ]; then
+            echo "exactly one branch required to release kork, but there are none"
+            exit 1
+          fi
+          NUM_BRANCHES=$(($(echo "$BRANCHES" | wc -l)))
+          echo "NUM_BRANCHES is '${NUM_BRANCHES}'"
+          if [ $NUM_BRANCHES -ne 1 ]; then
+            echo "exactly one branch required to release kork, but there are $NUM_BRANCHES ($BRANCHES)"
+            exit 1
+          fi
+          echo "exactly one branch ($BRANCHES)"
+
+
